# Generated by Django 2.2.3 on 2019-07-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20190706_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='platforms',
            new_name='platform',
        ),
    ]
